name: Integration Checks

on:
  [push, pull_request]

jobs:
  testing-code:
    name: Testing source code
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout branch
        uses: actions/checkout@v2
      - 
        name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}
      -
        name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      -
        name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .
      -
        name: Run unit tests
        run: python -m pytest

